apiVersion: apps/v1
kind: Deployment
metadata:
  name: bully-app
  labels:
    app: bully-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bully-app
  template:
    metadata:
      labels:
        app: bully-app
    spec:
      containers:
      - name: bully-container
        image: bully-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
      
      - name: flask-web-container
        image: flask-web-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
              
             


        
       