apiVersion: v1
kind : Service
metadata:
  name: flask-web-service
spec:
  type: NodePort
  selector:
    app: bully-app
    leader: "false"
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
